language: elixir

elixir:
  - 1.3.2

otp_release:
  - 18.2.1

services:
  - postgresql


sudo: required
dist: trusty

install:
  - mkdir tools
  - cd tools
  - wget http://download.geteventstore.com/binaries/EventStore-OSS-Ubuntu-14.04-v3.9.2.tar.gz
  - tar -xzf EventStore-OSS-Ubuntu-14.04-v3.9.2.tar.gz
  - cd EventStore-OSS-Ubuntu-14.04-v3.9.2
